default:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: DEV
      warehouse: ADAPTIVE_WH
      database: NBA_MONTE_CARLO
      schema: PUBLIC
      account: ''
      user: ''
    tools:
      type: snowflake
      role: PROD
      warehouse: ADAPTIVE_WH
      database: NBA_MONTE_CARLO
      schema: PUBLIC
      account: ''
      user: '' 
    prod:
      type: snowflake
      role: PROD
      warehouse: NBA_MONTE_CARLO_WH
      database: NBA_MONTE_CARLO
      schema: PUBLIC
      account: ''
      user: ''
